server:
  port: 9091
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.db.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.db.mapper: debug

dubbo: 
  scan: 
    basePackages: com.db
  application: 
    name: provider-dbmanage #定义服务名称
  registry: 
    address: zookeeper://192.168.21.130:2182?backup=192.168.21.130:2183,192.168.21.130:2184 # 集群
  protocol: 
    name: dubbo     #变量名一般固定
    port: 20891     #生产者的端口号
    